ARG DOMAIN="docker.io"
ARG ORG="cloudbsd"
ARG SRCIMAGENAME="freebsd-build-pkg"
ARG FREEBSD_RELEASE="14.3"
ARG ARCHITECTURE="amd64"
ARG PORT="java/openjdk8"
FROM ${DOMAIN}/${ORG}/${SRCIMAGENAME}-${ARCHITECTURE}:${FREEBSD_RELEASE}

ARG DOMAIN
ARG ORG
ARG SRCIMAGENAME
ARG FREEBSD_RELEASE
ARG ARCHITECTURE
ARG PORT

RUN env ASSUME_ALWAYS_YES=yes IGNORE_OS_VERSION=yes pkg update && \
    env ASSUME_ALWAYS_YES=yes IGNORE_OS_VERSION=yes pkg install -y ${PORT} || \
    (echo "Package installation failed, will build from source" && \
     cd /usr/ports/${PORT} && \
     make BATCH=YES install )

